apiVersion: application.kubero.dev/v1alpha1
kind: KuberoApp
metadata:
    name: firefox
    annotations:
        kubero.dev/template.architecture: '["linux/amd64", "linux/arm64", "linux/arm/v7", "linux/386"]'
        kubero.dev/template.description: "Start a Firefox web browser in a Docker container"
        kubero.dev/template.icon: "https://avatars.githubusercontent.com/u/109460230"
        kubero.dev/template.installation: ""
        kubero.dev/template.links: "[]"
        kubero.dev/template.screenshots: "[]"
        kubero.dev/template.source: "https://github.com/jlesage/docker-firefox"
        kubero.dev/template.categories: '["security", "utility"]'
        kubero.dev/template.title: "Firefox"
        kubero.dev/template.website: "https://www.mozilla.org/en-US/firefox/new/"
    labels:
        manager: kubero
spec:
    name: firefox
    deploymentstrategy: docker
    envVars: []
    extraVolumes:
        - accessMode: ReadWriteOnce
          accessModes:
              - ReadWriteOnce
          emptyDir: false
          mountPath: /config
          name: firefox-volume
          size: 1Gi
          storageClass: standard
    cronjobs: []
    addons: []
    web:
        replicaCount: 1
    worker:
        replicaCount: 0
    image:
        containerPort: "5800"
        pullPolicy: Always
        repository: jlesage/firefox
        tag: latest